### ISSUE TITLE
docker compose for arduino may need devices

### ISSUE THREAD

**Issue by kfessel** [Cross-Lab-Project/openLabs#1]
```
version: '3'
services:
  pyxtermjs:
    image: crosslab/edrys_pyxtermjs:latest
    ports:
      - "5000:5000"
    environment:
      - PYXTERM_CMD=zsh
    devices:
      - /dev/ttyACM0
```
